// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CRUDTesteConsultaAltera {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new EdgeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
	public void testeConsultaAlterar() {

		WebDriver browser = new EdgeDriver();
		browser.navigate().to("http://localhost:8080/les-ecommerce-vinhos/areaAdministrador/Clientes.html");

		WebElement campoNome = browser.findElement(By.id("nome"));
		campoNome.sendKeys("Rodrigo Rocha");

		WebElement botaoConsultar = browser.findElement(By.id("btnBuscar"));
		botaoConsultar.click();

		WebElement botaoEditar = browser.findElement(By.id("BotaoEditar"));

		JavascriptExecutor executor = (JavascriptExecutor) browser;
		executor.executeScript("arguments[0].click();", botaoEditar);

		// Dados pessoais
		WebElement campoNome2 = browser.findElement(By.id("typeNome"));
		campoNome2.clear();
		campoNome2.sendKeys("Rodrigo Rocha Silva");

		WebElement campoEmail = browser.findElement(By.id("typeEmail"));
		campoEmail.clear();
		campoEmail.sendKeys("rodrigorochaSilva@gmail.com");

		WebElement botaoAtualizar = browser.findElement(By.className("button-salvar"));
		botaoAtualizar.click();
		browser.navigate().to("http://localhost:8080/les-ecommerce-vinhos/areaAdministrador/Clientes.html");

	}

}