
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class FLUXODEVENDACENARIO12 {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		String driverPath = "src/main/resources/drivers/msedgedriver.exe";

		System.setProperty("webdriver.edge.driver", driverPath);
		driver = new EdgeDriver();
		driver.manage().window().maximize();
		vars = new HashMap<>();
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void fLUXODEVENDA() {
		driver.get("http://localhost:8080/les-ecommerce-vinhos/paginaInical.html");
		driver.manage().window().setSize(new Dimension(1936, 1056));
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}

		driver.findElement(By.id("btn-add-carrinho-5")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.switchTo().alert().accept();
		
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.linkText("MEU CARRINHO")).click();
		driver.findElement(By.id("btn-finalizar-compra")).click();
		
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.cssSelector(".col-md-3 > .btn")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("NovoEndereco")).click();
		{
			WebElement element = driver.findElement(By.id("NovoEndereco"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("nome")).click();
		driver.findElement(By.id("nome")).sendKeys("Teste3");
		driver.findElement(By.id("typeTipoResidencia")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		{
			WebElement dropdown = driver.findElement(By.id("typeTipoResidencia"));
			dropdown.findElement(By.xpath("//option[. = 'Casa']")).click();
		}
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("typeTipoLogradouro")).click();
		{
			WebElement dropdown = driver.findElement(By.id("typeTipoLogradouro"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("typeLogradouro")).click();
		driver.findElement(By.id("typeLogradouro")).click();
		driver.findElement(By.id("typeLogradouro")).sendKeys("Teste");
		driver.findElement(By.id("typeNumero")).click();
		driver.findElement(By.id("typeNumero")).sendKeys("32");
		driver.findElement(By.id("typeBairro")).click();
		driver.findElement(By.id("typeBairro")).sendKeys("Vila");
		driver.findElement(By.id("typeCidade")).click();
		driver.findElement(By.id("typeCidade")).sendKeys("Poa");
		driver.findElement(By.id("typeEstado")).click();
		driver.findElement(By.id("typeEstado")).sendKeys("SP");
		driver.findElement(By.id("typeCep")).click();
		driver.findElement(By.id("typeCep")).sendKeys("08559410");
		driver.findElement(By.id("typePais")).click();
		driver.findElement(By.id("typePais")).sendKeys("Brasil");
		driver.findElement(By.id("observacoes")).click();
		driver.findElement(By.id("observacoes")).sendKeys("nenhuma");
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.xpath("(//button[@id=\'BotaoCadastrar\'])[2]")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.switchTo().alert().accept();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("modalCadastroEndereco")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("fechar")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("SelecionarPagamento")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.id("valorCartao")).click();
		driver.findElement(By.id("valorCartao")).sendKeys("200");
		driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
		driver.findElement(By.cssSelector(".col-md-5 > .btn")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		{
			WebElement element = driver.findElement(By.cssSelector(".col-md-5 > .btn"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.id("valorCartao")).click();
		driver.findElement(By.id("valorCartao")).sendKeys("70.32");
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
		driver.switchTo().alert().accept();
		driver.findElement(By.cssSelector("#modalCartoes .card:nth-child(2) label")).click();
		driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
		
		driver.findElement(By.id("FinalizarCompra")).click();
	}

}
