
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class FLUXODEVENDACENARIO21 {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		String driverPath = "src/main/resources/drivers/msedgedriver.exe";

		System.setProperty("webdriver.edge.driver", driverPath);
		driver = new EdgeDriver();
		driver.manage().window().maximize();
		vars = new HashMap<>();
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void fLUXODEVENDA() {
		driver.get("http://localhost:8080/les-ecommerce-vinhos/paginaInical.html");
		driver.manage().window().setSize(new Dimension(1936, 1056));
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		driver.findElement(By.id("btn-add-carrinho-2")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		driver.switchTo().alert().accept();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.linkText("MEU CARRINHO")).click();
	    driver.findElement(By.id("btn-finalizar-compra")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.cssSelector(".col-md-3 > .btn")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("NovoEndereco")).click();
		
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    {
	      WebElement element = driver.findElement(By.tagName("body"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element, 0, 0).perform();
	    }
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("nome")).click();
	    driver.findElement(By.id("nome")).sendKeys("Teste4");
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.cssSelector(".row:nth-child(2) > .col-md-6:nth-child(2)")).click();
	    driver.findElement(By.id("typeTipoResidencia")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("typeTipoResidencia"));
	      dropdown.findElement(By.xpath("//option[. = 'Apartamento']")).click();
	    }
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("typeTipoLogradouro")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("typeTipoLogradouro"));
	      dropdown.findElement(By.xpath("//option[. = 'Estrada']")).click();
	    }
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("typeLogradouro")).click();
	    driver.findElement(By.id("typeLogradouro")).sendKeys("Teste");
	    driver.findElement(By.id("typeNumero")).click();
	    driver.findElement(By.id("typeNumero")).sendKeys("32");
	    driver.findElement(By.id("typeBairro")).click();
	    driver.findElement(By.id("typeBairro")).sendKeys("Vila");
	    driver.findElement(By.id("typeCidade")).click();
	    driver.findElement(By.id("typeCidade")).sendKeys("Poa");
	    driver.findElement(By.id("typeCidade")).click();
	    driver.findElement(By.id("typeCidade")).sendKeys("Mogi das Cruzes");
	    driver.findElement(By.id("typeEstado")).click();
	    driver.findElement(By.id("typeEstado")).sendKeys("SP");
	    driver.findElement(By.id("typeCep")).click();
	    driver.findElement(By.id("typeCep")).sendKeys("08559410");
	    driver.findElement(By.id("typePais")).click();
	    driver.findElement(By.id("typePais")).sendKeys("Brasil");
	    driver.findElement(By.id("observacoes")).click();
	    driver.findElement(By.id("observacoes")).sendKeys("nenhuma");
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.xpath("(//button[@id=\'BotaoCadastrar\'])[2]")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		driver.switchTo().alert().accept();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.cssSelector("#fechar > span")).click();
	    driver.findElement(By.id("SelecionarCupons")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("cupomTselect1")).click();
	    driver.findElement(By.id("SalvarCupom")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("SelecionarCupons")).click();
	    {
	      WebElement element = driver.findElement(By.id("SelecionarCupons"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element).perform();
	    }
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    {
	      WebElement element = driver.findElement(By.tagName("body"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element, 0, 0).perform();
	    }
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.cssSelector(".card:nth-child(8) #cupomTselect4")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.cssSelector(".card:nth-child(7) .custom-checkbox")).click();
	    driver.findElement(By.id("cupomTselect4")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("SalvarCupom")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("SelecionarPagamento")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    driver.findElement(By.id("valorCartao")).click();
	    driver.findElement(By.id("valorCartao")).sendKeys("75.04");
	    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		driver.switchTo().alert().accept();
	    driver.findElement(By.cssSelector("#modalCartoes .card:nth-child(2) label")).click();
	    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
	    {
	      WebElement element = driver.findElement(By.tagName("body"));
	      Actions builder = new Actions(driver);
	      builder.moveToElement(element, 0, 0).perform();
	    }
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		driver.findElement(By.id("FinalizarCompra")).click();

	}
}
