// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;


public class FLUXODEVENDAERROS {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
	public void setUp() {
		String driverPath = "src/main/resources/drivers/msedgedriver.exe";

		System.setProperty("webdriver.edge.driver", driverPath);
		driver = new EdgeDriver();
		driver.manage().window().maximize();
		vars = new HashMap<>();
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}
  @Test
  public void fLUXODEVENDA() {
    driver.get("http://localhost:8080/les-ecommerce-vinhos/paginaInical.html");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("btn-add-carrinho-2")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
    driver.findElement(By.id("btn-add-carrinho-3")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
    driver.findElement(By.linkText("MEU CARRINHO")).click();
    driver.findElement(By.cssSelector(".col-12:nth-child(3) .d-grid > .btn")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
    driver.findElement(By.id("btn-incrementar-0")).click();
    driver.findElement(By.cssSelector(".col-12:nth-child(4) .d-grid > .btn")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
    driver.findElement(By.id("btn-finalizar-compra")).click();
    driver.findElement(By.cssSelector(".col-md-3 > .btn")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.cssSelector("#modalSelecaoEndereco .card:nth-child(1) label")).click();
    driver.findElement(By.id("SalvarEndereco")).click();
    driver.findElement(By.cssSelector(".col-md-3 > .btn")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.cssSelector("#modalSelecaoEndereco .card:nth-child(2) label")).click();
    driver.findElement(By.id("SalvarEndereco")).click();
    driver.findElement(By.id("SelecionarCupons")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.id("cupomTselect1")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) .col-md-1")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) #cupomTselect1")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
    driver.findElement(By.id("SalvarCupom")).click();
    {
      WebElement element = driver.findElement(By.id("SalvarCupom"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.cssSelector(".col-md-5 > .btn")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.cssSelector("#modalCartoes .card:nth-child(1) label")).click();
    driver.findElement(By.id("valorCartao")).click();
    driver.findElement(By.id("valorCartao")).sendKeys("200");
    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
    driver.findElement(By.cssSelector(".col-md-5 > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-md-5 > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.cssSelector("#modalCartoes .card:nth-child(1) label")).click();
    driver.findElement(By.id("valorCartao")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.id("valorCartao")).sendKeys("100");
    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
	driver.switchTo().alert().accept();
	
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.id("valorCartao")).click();
    driver.findElement(By.id("valorCartao")).sendKeys("5");
    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
	driver.switchTo().alert().accept();
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.id("valorCartao")).click();
    driver.findElement(By.id("valorCartao")).sendKeys("80");
    driver.findElement(By.id("valorCartao")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-6 > .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".CartoesSection:nth-child(2) > .row .Botao2")).click();
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    {
      WebElement element = driver.findElement(By.id("valorCartao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    driver.findElement(By.id("valorCartao")).click();
    driver.findElement(By.id("valorCartao")).sendKeys("98.8");
    driver.findElement(By.cssSelector(".col-6 > .btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-6 > .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
	try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
