
// Generated by Selenium IDE
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
public class TestSuitExec {
	
	@RunWith(Suite.class)
	@Suite.SuiteClasses({
		//FLUXODEVENDACancela.class,
		//FLUXODEVENDATest.class,
		//FLUXODEVENDAERROS.class,
		FLUXODEVENDACENARIO1.class,
	    FLUXODEVENDACENARIO12.class,
	    FLUXODEVENDACENARIO2.class,
	    FLUXODEVENDACENARIO21.class,
	    FLUXODEVENDACENARIO3.class,
	    FLUXODEVENDACENARIO31.class,
	    FLUXODEVENDACENARIO32.class,
	    FLUXODEVENDACENARIO4.class,
	    FLUXODEVENDACENARIO41.class,

	})
	public class TestSuite {
	    // Esta classe permanece vazia, usada apenas como um cont�iner para as anota��es acima
	}

}
